/*
1-Lista el total de facturas de un cliente/a en un período determinado.
Se va a listar el total de facturas del cliente 10
*/

SELECT vt.FECHA_REGISTRO AS FECHA,vt.FACTURA_VENTA AS FACTURA, cl.NOMBRE,CONCAT(vd.NOMBRE,' ', vd.APELLIDO) AS VENDEDOR,
dv.CANTIDAD, dv.PRECIO,
(SELECT SUM(dv.PRECIO * dv.CANTIDAD) WHERE vt.ID_VENTA = dv.ID_VENTA) AS TOTAL
FROM TBL_VENTA vt
INNER JOIN TBL_CLIENTE cl ON vt.ID_CLIENTE = cl.ID_CLIENTE
INNER JOIN TBL_VENDEDOR vd ON vt.ID_VENDEDOR = vd.ID_VENDEDOR
INNER JOIN TBL_DETALLE_VENTA  dv ON vt.ID_VENTA = dv.ID_VENTA
INNER JOIN TBL_GAFA tg on dv.ID_GAFA = tg.ID_GAFA
WHERE cl.ID_CLIENTE =10 
AND vt.FECHA_REGISTRO BETWEEN '2023-01-01' AND '2023-08-01'
GROUP BY vt.FACTURA_VENTA
ORDER BY vt.FACTURA_VENTA;