SELECT COUNT(dp.CANTIDAD) AS 'Bebidas vendidas en Ciudad de Barcelona'
FROM TBL_PEDIDO pd
INNER JOIN TBL_DETALLE_PEDIDO dp on pd.ID_PEDIDO = dp.ID_PEDIDO
INNER JOIN TBL_PRODUCTO pr on dp.ID_PRODUCTO = pr.ID_PRODUCTO
INNER JOIN TBL_PRODUCTO_CATEGORIA pc on dp.ID_PRODUCTO = pc.ID_PRODUCTO
INNER JOIN TBL_CATEGORIA ca on pc.ID_CATEGORIA = ca.ID_CATEGORIA
INNER JOIN TBL_CLIENTE ci on pd.ID_CLIENTE = ci.ID_CLIENTE
INNER JOIN TBL_LOCALIDAD lo on ci.ID_LOCALIDAD = lo.ID_LOCALIDAD
WHERE ca.NOMBRE = 'Bebidas' AND lo.LOCALIDAD = 'Ciudad Barcelona'

